# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 581)
        MainWindow.setStyleSheet("font-family: Noto Sans SC;\n"
"background-color: qradialgradient(cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 191, 255, 255), stop:1 rgba(0, 0, 128, 255));\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;")
        self.frame.setObjectName("frame")
        self.hl_search = QtWidgets.QHBoxLayout(self.frame)
        self.hl_search.setObjectName("hl_search")
        self.lb_name_pr = QtWidgets.QLabel(parent=self.frame)
        self.lb_name_pr.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(13)
        self.lb_name_pr.setFont(font)
        self.lb_name_pr.setStyleSheet("color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,0);\n"
"     border: 1px solid rgba(255,255,255,0);\n"
"     border-radius:7px;\n"
"width: 230;\n"
"height: 30;")
        self.lb_name_pr.setObjectName("lb_name_pr")
        self.hl_search.addWidget(self.lb_name_pr)
        self.le_name = QtWidgets.QLineEdit(parent=self.frame)
        self.le_name.setMaximumSize(QtCore.QSize(12313, 100))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(11)
        self.le_name.setFont(font)
        self.le_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,150);\n"
"     border-radius:7px;\n"
"width: 230;\n"
"height: 25;")
        self.le_name.setObjectName("le_name")
        self.hl_search.addWidget(self.le_name)
        self.verticalLayout.addWidget(self.frame)
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setStyleSheet("\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"background-color: white; \n"
"color: black;\n"
"gridline-color: qradialgradient(cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 191, 255, 255), stop:1 rgba(0, 0, 128, 255));\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #555555;\n"
"    color: #ffffff;\n"
"    border:none;\n"
"}\n"
"")
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setStyleSheet("background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;")
        self.groupBox.setObjectName("groupBox")
        self.hl_buts_action = QtWidgets.QHBoxLayout(self.groupBox)
        self.hl_buts_action.setObjectName("hl_buts_action")
        self.but_open = QtWidgets.QPushButton(parent=self.groupBox)
        self.but_open.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(9)
        self.but_open.setFont(font)
        self.but_open.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.but_open.setAutoFillBackground(False)
        self.but_open.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"width: 230;\n"
"height: 30;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,150);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/open_in_new_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_open.setIcon(icon)
        self.but_open.setIconSize(QtCore.QSize(24, 24))
        self.but_open.setObjectName("but_open")
        self.hl_buts_action.addWidget(self.but_open)
        self.but_redac = QtWidgets.QPushButton(parent=self.groupBox)
        self.but_redac.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(9)
        self.but_redac.setFont(font)
        self.but_redac.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"width: 230;\n"
"height: 30;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,150);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/edit_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_redac.setIcon(icon1)
        self.but_redac.setIconSize(QtCore.QSize(24, 24))
        self.but_redac.setObjectName("but_redac")
        self.hl_buts_action.addWidget(self.but_redac)
        self.but_add = QtWidgets.QPushButton(parent=self.groupBox)
        self.but_add.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(9)
        self.but_add.setFont(font)
        self.but_add.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.but_add.setAutoFillBackground(False)
        self.but_add.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"width: 230;\n"
"height: 30;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,150);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/post_add_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_add.setIcon(icon2)
        self.but_add.setIconSize(QtCore.QSize(24, 24))
        self.but_add.setObjectName("but_add")
        self.hl_buts_action.addWidget(self.but_add)
        self.but_delete = QtWidgets.QPushButton(parent=self.groupBox)
        self.but_delete.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(9)
        self.but_delete.setFont(font)
        self.but_delete.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"width: 230;\n"
"height: 30;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,150);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/delete_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_delete.setIcon(icon3)
        self.but_delete.setIconSize(QtCore.QSize(24, 24))
        self.but_delete.setObjectName("but_delete")
        self.hl_buts_action.addWidget(self.but_delete)
        self.but_search = QtWidgets.QPushButton(parent=self.groupBox)
        self.but_search.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(9)
        self.but_search.setFont(font)
        self.but_search.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"width: 230;\n"
"height: 30;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,150);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/search_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_search.setIcon(icon4)
        self.but_search.setIconSize(QtCore.QSize(24, 24))
        self.but_search.setObjectName("but_search")
        self.hl_buts_action.addWidget(self.but_search)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0); \n"
"border:None\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.hl_buts_action.addWidget(self.label_2)
        self.but_order = QtWidgets.QPushButton(parent=self.groupBox)
        self.but_order.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(11)
        self.but_order.setFont(font)
        self.but_order.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"width: 230;\n"
"height: 30;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,150);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/add_circle_outline_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_order.setIcon(icon5)
        self.but_order.setIconSize(QtCore.QSize(24, 24))
        self.but_order.setObjectName("but_order")
        self.hl_buts_action.addWidget(self.but_order)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 22))
        self.menubar.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"")
        self.menubar.setObjectName("menubar")
        self.m_tables = QtWidgets.QMenu(parent=self.menubar)
        self.m_tables.setObjectName("m_tables")
        self.m_about = QtWidgets.QMenu(parent=self.menubar)
        self.m_about.setObjectName("m_about")
        self.m_exit = QtWidgets.QMenu(parent=self.menubar)
        self.m_exit.setObjectName("m_exit")
        MainWindow.setMenuBar(self.menubar)
        self.actiontables = QtGui.QAction(parent=MainWindow)
        self.actiontables.setObjectName("actiontables")
        self.actionorders = QtGui.QAction(parent=MainWindow)
        self.actionorders.setObjectName("actionorders")
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.actionexit = QtGui.QAction(parent=MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_orders = QtGui.QAction(parent=MainWindow)
        self.action_orders.setObjectName("action_orders")
        self.action_workers = QtGui.QAction(parent=MainWindow)
        self.action_workers.setObjectName("action_workers")
        self.action_products = QtGui.QAction(parent=MainWindow)
        self.action_products.setObjectName("action_products")
        self.action_about = QtGui.QAction(parent=MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_exit = QtGui.QAction(parent=MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.m_tables.addAction(self.action_orders)
        self.m_tables.addAction(self.action_workers)
        self.m_tables.addAction(self.action_products)
        self.m_about.addAction(self.action_about)
        self.m_exit.addAction(self.action_exit)
        self.menubar.addAction(self.m_tables.menuAction())
        self.menubar.addAction(self.m_about.menuAction())
        self.menubar.addAction(self.m_exit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_name_pr.setText(_translate("MainWindow", "ID"))
        self.but_open.setText(_translate("MainWindow", "Открыть"))
        self.but_redac.setText(_translate("MainWindow", "Изменить"))
        self.but_add.setText(_translate("MainWindow", "Добавить"))
        self.but_delete.setText(_translate("MainWindow", "Удалить"))
        self.but_search.setText(_translate("MainWindow", "Найти"))
        self.but_order.setText(_translate("MainWindow", "Собрать заказ"))
        self.m_tables.setTitle(_translate("MainWindow", "Таблицы"))
        self.m_about.setTitle(_translate("MainWindow", "О программе"))
        self.m_exit.setTitle(_translate("MainWindow", "Выход"))
        self.actiontables.setText(_translate("MainWindow", "tables"))
        self.actionorders.setText(_translate("MainWindow", "orders"))
        self.action.setText(_translate("MainWindow", "about program"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.action_2.setText(_translate("MainWindow", "Запросы"))
        self.action_orders.setText(_translate("MainWindow", "Заказы"))
        self.action_workers.setText(_translate("MainWindow", "Сотрудники"))
        self.action_products.setText(_translate("MainWindow", "Товары"))
        self.action_about.setText(_translate("MainWindow", "О программы"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))

