# Form implementation generated from reading ui file 'mainW.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 420)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setStyleSheet("")
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.hl_search = QtWidgets.QHBoxLayout()
        self.hl_search.setObjectName("hl_search")
        self.cb_search = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cb_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cb_search.setStyleSheet("")
        self.cb_search.setObjectName("cb_search")
        self.hl_search.addWidget(self.cb_search)
        self.le_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_name.setMaximumSize(QtCore.QSize(200, 100))
        self.le_name.setStyleSheet("border-radius: 7px;\n"
"border-color: rgb(0, 0, 0);\n"
"border: 1px solid gray;\n"
"")
        self.le_name.setObjectName("le_name")
        self.hl_search.addWidget(self.le_name)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.hl_search.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.hl_search)
        self.hl_buts_action = QtWidgets.QHBoxLayout()
        self.hl_buts_action.setObjectName("hl_buts_action")
        self.but_redac = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_redac.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(9)
        self.but_redac.setFont(font)
        self.but_redac.setStyleSheet("QPushButton{\n"
"height:20px;}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/edit_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_redac.setIcon(icon)
        self.but_redac.setIconSize(QtCore.QSize(24, 24))
        self.but_redac.setObjectName("but_redac")
        self.hl_buts_action.addWidget(self.but_redac)
        self.but_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_add.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(9)
        self.but_add.setFont(font)
        self.but_add.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.but_add.setAutoFillBackground(False)
        self.but_add.setStyleSheet("QPushButton{\n"
"height:20px;}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/post_add_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_add.setIcon(icon1)
        self.but_add.setIconSize(QtCore.QSize(24, 24))
        self.but_add.setObjectName("but_add")
        self.hl_buts_action.addWidget(self.but_add)
        self.but_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_delete.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(9)
        self.but_delete.setFont(font)
        self.but_delete.setStyleSheet("QPushButton{\n"
"height:20px;}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/delete_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_delete.setIcon(icon2)
        self.but_delete.setIconSize(QtCore.QSize(24, 24))
        self.but_delete.setObjectName("but_delete")
        self.hl_buts_action.addWidget(self.but_delete)
        self.but_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_search.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(9)
        self.but_search.setFont(font)
        self.but_search.setStyleSheet("QPushButton{\n"
"height:20px;}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/print_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_search.setIcon(icon3)
        self.but_search.setIconSize(QtCore.QSize(24, 24))
        self.but_search.setObjectName("but_search")
        self.hl_buts_action.addWidget(self.but_search)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.hl_buts_action.addWidget(self.label_2)
        self.but_excel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_excel.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(11)
        self.but_excel.setFont(font)
        self.but_excel.setStyleSheet("QPushButton{\n"
"background-color: rgb(223, 223, 223);\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"width:230px;\n"
"height:30px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        self.but_excel.setIcon(icon3)
        self.but_excel.setIconSize(QtCore.QSize(24, 24))
        self.but_excel.setObjectName("but_excel")
        self.hl_buts_action.addWidget(self.but_excel)
        self.verticalLayout.addLayout(self.hl_buts_action)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 26))
        self.menubar.setObjectName("menubar")
        self.m_tables = QtWidgets.QMenu(parent=self.menubar)
        self.m_tables.setObjectName("m_tables")
        self.m_about = QtWidgets.QMenu(parent=self.menubar)
        self.m_about.setObjectName("m_about")
        self.m_exit = QtWidgets.QMenu(parent=self.menubar)
        self.m_exit.setObjectName("m_exit")
        MainWindow.setMenuBar(self.menubar)
        self.actiontables = QtGui.QAction(parent=MainWindow)
        self.actiontables.setObjectName("actiontables")
        self.actionorders = QtGui.QAction(parent=MainWindow)
        self.actionorders.setObjectName("actionorders")
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.actionexit = QtGui.QAction(parent=MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_orders = QtGui.QAction(parent=MainWindow)
        self.action_orders.setObjectName("action_orders")
        self.action_workers = QtGui.QAction(parent=MainWindow)
        self.action_workers.setObjectName("action_workers")
        self.action_pck = QtGui.QAction(parent=MainWindow)
        self.action_pck.setObjectName("action_pck")
        self.action_request = QtGui.QAction(parent=MainWindow)
        self.action_request.setObjectName("action_request")
        self.action_about = QtGui.QAction(parent=MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_exit = QtGui.QAction(parent=MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.m_tables.addAction(self.action_pck)
        self.m_about.addAction(self.action_about)
        self.m_exit.addAction(self.action_exit)
        self.menubar.addAction(self.m_tables.menuAction())
        self.menubar.addAction(self.m_about.menuAction())
        self.menubar.addAction(self.m_exit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.but_redac.setText(_translate("MainWindow", "Изменить"))
        self.but_add.setText(_translate("MainWindow", "Новый"))
        self.but_delete.setText(_translate("MainWindow", "Удалить"))
        self.but_search.setText(_translate("MainWindow", "Найти"))
        self.but_excel.setText(_translate("MainWindow", "Вывести в EXCEL"))
        self.m_tables.setTitle(_translate("MainWindow", "Таблицы"))
        self.m_about.setTitle(_translate("MainWindow", "О программе"))
        self.m_exit.setTitle(_translate("MainWindow", "Выход"))
        self.actiontables.setText(_translate("MainWindow", "tables"))
        self.actionorders.setText(_translate("MainWindow", "orders"))
        self.action.setText(_translate("MainWindow", "about program"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.action_2.setText(_translate("MainWindow", "Запросы"))
        self.action_orders.setText(_translate("MainWindow", "Заказы"))
        self.action_workers.setText(_translate("MainWindow", "Сотрудники"))
        self.action_pck.setText(_translate("MainWindow", "ПЦК"))
        self.action_request.setText(_translate("MainWindow", "Запросы"))
        self.action_about.setText(_translate("MainWindow", "О программы"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))
