# Form implementation generated from reading ui file 'dis_wid_report.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_report(object):
    def setupUi(self, Dialog_report):
        Dialog_report.setObjectName("Dialog_report")
        Dialog_report.resize(505, 240)
        Dialog_report.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.539773 rgba(14, 23, 106, 255), stop:1 rgba(85, 170, 255, 255));\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font-family: Noto Sans SC;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_report)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Dialog_report)
        self.frame.setStyleSheet("background-color: rgba(255, 255 ,255 ,30 );\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px;")
        self.frame.setObjectName("frame")
        self.layout_param = QtWidgets.QVBoxLayout(self.frame)
        self.layout_param.setObjectName("layout_param")
        self.cb_name_report = QtWidgets.QComboBox(parent=self.frame)
        self.cb_name_report.setMaximumSize(QtCore.QSize(3203402, 4563456))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(10)
        self.cb_name_report.setFont(font)
        self.cb_name_report.setStyleSheet("border-radius: 5px;\n"
"\n"
"border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"width:230px;\n"
"height:40px;")
        self.cb_name_report.setObjectName("cb_name_report")
        self.layout_param.addWidget(self.cb_name_report)
        self.date_start = QtWidgets.QDateEdit(parent=self.frame)
        self.date_start.setMaximumSize(QtCore.QSize(16777215, 4356435))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.date_start.setFont(font)
        self.date_start.setStyleSheet("border-radius: 5px;\n"
"\n"
"border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"width:230px;\n"
"height:40px;")
        self.date_start.setObjectName("date_start")
        self.layout_param.addWidget(self.date_start)
        self.date_end = QtWidgets.QDateEdit(parent=self.frame)
        self.date_end.setMaximumSize(QtCore.QSize(16777215, 234235))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.date_end.setFont(font)
        self.date_end.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"width:230px;\n"
"height:40px;")
        self.date_end.setObjectName("date_end")
        self.layout_param.addWidget(self.date_end)
        self.verticalLayout_2.addWidget(self.frame)
        self.but_save_add = QtWidgets.QPushButton(parent=Dialog_report)
        self.but_save_add.setEnabled(True)
        self.but_save_add.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(14)
        self.but_save_add.setFont(font)
        self.but_save_add.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res-add/icons/post_add_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_save_add.setIcon(icon)
        self.but_save_add.setIconSize(QtCore.QSize(30, 30))
        self.but_save_add.setObjectName("but_save_add")
        self.verticalLayout_2.addWidget(self.but_save_add)

        self.retranslateUi(Dialog_report)
        QtCore.QMetaObject.connectSlotsByName(Dialog_report)

    def retranslateUi(self, Dialog_report):
        _translate = QtCore.QCoreApplication.translate
        Dialog_report.setWindowTitle(_translate("Dialog_report", "Dialog"))
        self.but_save_add.setText(_translate("Dialog_report", "📑Cформировать"))
