# Form implementation generated from reading ui file 'mainW.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1728, 594)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.539773 rgba(14, 23, 106, 255), stop:1 rgba(85, 170, 255, 255));\n"
"background-color: rgb(11, 11, 11);\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font-family: Noto Sans SC;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(255, 255 ,255 ,0 );\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hl_buts_action = QtWidgets.QHBoxLayout()
        self.hl_buts_action.setObjectName("hl_buts_action")
        self.but_profile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_profile.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(16)
        self.but_profile.setFont(font)
        self.but_profile.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.but_profile.setAutoFillBackground(False)
        self.but_profile.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/post_add_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_profile.setIcon(icon)
        self.but_profile.setIconSize(QtCore.QSize(24, 24))
        self.but_profile.setObjectName("but_profile")
        self.hl_buts_action.addWidget(self.but_profile)
        self.but_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_add.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.but_add.setFont(font)
        self.but_add.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.but_add.setAutoFillBackground(False)
        self.but_add.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        self.but_add.setIcon(icon)
        self.but_add.setIconSize(QtCore.QSize(24, 24))
        self.but_add.setObjectName("but_add")
        self.hl_buts_action.addWidget(self.but_add)
        self.but_redac = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_redac.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.but_redac.setFont(font)
        self.but_redac.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/edit_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_redac.setIcon(icon1)
        self.but_redac.setIconSize(QtCore.QSize(24, 24))
        self.but_redac.setObjectName("but_redac")
        self.hl_buts_action.addWidget(self.but_redac)
        self.but_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_delete.setMaximumSize(QtCore.QSize(1251245, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.but_delete.setFont(font)
        self.but_delete.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/delete_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_delete.setIcon(icon2)
        self.but_delete.setIconSize(QtCore.QSize(24, 24))
        self.but_delete.setObjectName("but_delete")
        self.hl_buts_action.addWidget(self.but_delete)
        self.but_dogovor = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_dogovor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.but_dogovor.setFont(font)
        self.but_dogovor.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        self.but_dogovor.setIcon(icon1)
        self.but_dogovor.setIconSize(QtCore.QSize(24, 24))
        self.but_dogovor.setObjectName("but_dogovor")
        self.hl_buts_action.addWidget(self.but_dogovor)
        self.but_order = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_order.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.but_order.setFont(font)
        self.but_order.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/print_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_order.setIcon(icon3)
        self.but_order.setIconSize(QtCore.QSize(24, 24))
        self.but_order.setObjectName("but_order")
        self.hl_buts_action.addWidget(self.but_order)
        self.but_report = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_report.setEnabled(True)
        self.but_report.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.but_report.setFont(font)
        self.but_report.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res-add/icons/post_add_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.but_report.setIcon(icon4)
        self.but_report.setIconSize(QtCore.QSize(30, 30))
        self.but_report.setObjectName("but_report")
        self.hl_buts_action.addWidget(self.but_report)
        self.but_excel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_excel.setMaximumSize(QtCore.QSize(2415125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.but_excel.setFont(font)
        self.but_excel.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        self.but_excel.setIcon(icon3)
        self.but_excel.setIconSize(QtCore.QSize(24, 24))
        self.but_excel.setObjectName("but_excel")
        self.hl_buts_action.addWidget(self.but_excel)
        self.verticalLayout.addLayout(self.hl_buts_action)
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setStyleSheet("background-color: rgba(255, 255 ,255 ,30 );\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px;\n"
"")
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_search = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cb_search.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(10)
        self.cb_search.setFont(font)
        self.cb_search.setStyleSheet("\n"
"\n"
"border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"width:230px;\n"
"height:40px;")
        self.cb_search.setObjectName("cb_search")
        self.cb_search.addItem("")
        self.horizontalLayout.addWidget(self.cb_search)
        self.le_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_name.setMaximumSize(QtCore.QSize(9345349, 35))
        self.le_name.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"border: 1px solid gray;\n"
"color: rgb(0, 0, 0);\n"
"\n"
"border-radius: 10px;\n"
"width:230px;\n"
"height:40px;")
        self.le_name.setObjectName("le_name")
        self.horizontalLayout.addWidget(self.le_name)
        self.but_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_search.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        self.but_search.setFont(font)
        self.but_search.setStyleSheet("QPushButton{\n"
"background-color: rgba(255,255,255,30);\n"
"color: rgba(255, 255, 255, 255);\n"
"border-radius: 5px;\n"
"width:230px;\n"
"height:40px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,40);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,30);\n"
"}")
        self.but_search.setIcon(icon3)
        self.but_search.setIconSize(QtCore.QSize(24, 24))
        self.but_search.setObjectName("but_search")
        self.horizontalLayout.addWidget(self.but_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1728, 24))
        self.menubar.setObjectName("menubar")
        self.m_tables = QtWidgets.QMenu(parent=self.menubar)
        self.m_tables.setObjectName("m_tables")
        self.m_about = QtWidgets.QMenu(parent=self.menubar)
        self.m_about.setObjectName("m_about")
        self.m_exit = QtWidgets.QMenu(parent=self.menubar)
        self.m_exit.setObjectName("m_exit")
        MainWindow.setMenuBar(self.menubar)
        self.actiontables = QtGui.QAction(parent=MainWindow)
        self.actiontables.setObjectName("actiontables")
        self.actionorders = QtGui.QAction(parent=MainWindow)
        self.actionorders.setObjectName("actionorders")
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.actionexit = QtGui.QAction(parent=MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_orders = QtGui.QAction(parent=MainWindow)
        self.action_orders.setObjectName("action_orders")
        self.action_workers = QtGui.QAction(parent=MainWindow)
        self.action_workers.setObjectName("action_workers")
        self.action_pck = QtGui.QAction(parent=MainWindow)
        self.action_pck.setObjectName("action_pck")
        self.action_request = QtGui.QAction(parent=MainWindow)
        self.action_request.setObjectName("action_request")
        self.action_about = QtGui.QAction(parent=MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_exit = QtGui.QAction(parent=MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_report = QtGui.QAction(parent=MainWindow)
        self.action_report.setObjectName("action_report")
        self.m_about.addAction(self.action_about)
        self.m_exit.addAction(self.action_exit)
        self.menubar.addAction(self.m_tables.menuAction())
        self.menubar.addAction(self.m_about.menuAction())
        self.menubar.addAction(self.m_exit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.but_profile.setText(_translate("MainWindow", "👤"))
        self.but_add.setText(_translate("MainWindow", "➕ Новый"))
        self.but_redac.setText(_translate("MainWindow", "🖋️ Изменить"))
        self.but_delete.setText(_translate("MainWindow", "🗑️ Удалить"))
        self.but_dogovor.setText(_translate("MainWindow", "🤝 Договор"))
        self.but_order.setText(_translate("MainWindow", "📝 Оформить"))
        self.but_report.setText(_translate("MainWindow", "📑Отчеты"))
        self.but_excel.setText(_translate("MainWindow", "⬇️ EXCEL"))
        self.cb_search.setItemText(0, _translate("MainWindow", "Выберите"))
        self.but_search.setText(_translate("MainWindow", "🔍 Найти"))
        self.m_tables.setTitle(_translate("MainWindow", "Таблицы"))
        self.m_about.setTitle(_translate("MainWindow", "О программе"))
        self.m_exit.setTitle(_translate("MainWindow", "Выход"))
        self.actiontables.setText(_translate("MainWindow", "tables"))
        self.actionorders.setText(_translate("MainWindow", "orders"))
        self.action.setText(_translate("MainWindow", "about program"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.action_2.setText(_translate("MainWindow", "Запросы"))
        self.action_orders.setText(_translate("MainWindow", "Заказы"))
        self.action_workers.setText(_translate("MainWindow", "Сотрудники"))
        self.action_pck.setText(_translate("MainWindow", "ПЦК"))
        self.action_request.setText(_translate("MainWindow", "Запросы"))
        self.action_about.setText(_translate("MainWindow", "О программы"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))
        self.action_report.setText(_translate("MainWindow", "Отчеты"))
